import{S as h,i as L,a as b}from"./assets/vendor-bad0427b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const c=document.querySelector(".form"),u=document.querySelector(".gallery"),d=document.querySelector(".loader"),i=document.querySelector(".load_more_button");function w(){d.style.display="flex"}function p(){d.style.display="none"}function _(){i.style.display="flex"}function f(){i.style.display="none"}f();p();const v=()=>document.querySelector(".gallery_list").getBoundingClientRect().height,S=()=>{const r=v();window.scrollBy({top:r*2,behavior:"smooth"})},q=async r=>{try{return(await b.get("https://pixabay.com/api/?key=32445891-4e5aca6c6794ec22921e6fc5b",{params:r})).data}catch(t){console.log(t)}},$=r=>{let t=1;const s=40;let n=!1;return async()=>{try{if(n)return;const{hits:e,totalHits:o}=await q({q:r,page:t,per_page:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return _(),t>=o/s&&(f(),n=!0,L.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),t+=1,e}catch(e){console.log(e)}}},H=new h(".gallery_list a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function x(r){const t=r.reduce((s,{webformatURL:n,largeImageURL:e,tags:o,likes:a,views:y,comments:g,downloads:m})=>s+`
         <li class='gallery_list'>
          <a href="${e}"><img class='gallery_img'src="${n}" alt="${o}" /></a>
          <p class='gallery_info'>Likes <span>${a}</span></p>
          <p class='gallery_info'>Views <span>${y}</span></p>
          <p class='gallery_info'>Comments <span>${g}</span></p>
          <p class='gallery_info'>Downloads <span>${m}</span></p>
        </li>`,"");u.insertAdjacentHTML("beforeend",t),H.refresh()}let l=null;c.addEventListener("submit",async r=>{r.preventDefault(),l!=null&&i.removeEventListener("click",l);const t=c.querySelector(".form_input").value;u.innerHTML="";const s=$(t);let n=!0;l=async()=>{w();const e=await s();x(e),p(),n||S(),n=!1},await l(),i.addEventListener("click",l)});
//# sourceMappingURL=commonHelpers.js.map
